### ISSUE TITLE
chromedriver.zip is corrupted. 

### ISSUE THREAD

**Issue by ameybh** [vinaysomawat/Spam-WhatsApp-Contacts#1]
###error while trying to unzip chromedriver
First, the name in the readme is _chromedriver_linux64.zip_, while the file given is just _chromedriver_ .
Secondly, when run
```
unzip chromedriver
```
getting error short read.
Tried extracting manually, doesn't work.
Changed extension to zip from none, still doesn't work either.

**Comment by ameybh** [comment]
Ok, I got the issue, you have already extracted the file. Please update the readme.md corresponding to it.

**Comment by vinaysomawat** [comment]
@ameybhavsar24 Thanks to getting the issue. I would be happy if you contribute to this project and make a PR corresponding to it.

**Comment by ameybh** [comment]
Surely I will sometime in future.
